on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: build

jobs:
  build-deploy:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{secrets.GITHUB_TOKEN}}
      NOAA_KEY: ${{secrets.NOAA_KEY}}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: 'https://tbep-tech.r-universe.dev'
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true
          # uncomment below and fill to pin a version
          # version: 0.9.600
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse
            any::extrafont
            any::flextable
            any::gridExtra
            any::english
            any::here
            any::rmarkdown
            any::ggfx
            any::ggmap
            any::ggsn
            any::ggrepel
            any::knitr
            any::ftExtra
            tbeptools
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
